import * as XLSX from 'xlsx';
import { writeFileSync } from 'fs';

// Sample fuel transaction data matching the expected Excel format
const sampleData = [
    {
        "Store No": "911",
        "Bin No": "BIN001",
        "Item No": "FUEL001",
        "UOM Code": "L",
        "Item Desc": "Premium Petrol",
        "Item Cat": "Fuel",
        "Trans Date": "20260115",
        "Trans Type": "Issue",
        "Trans Qty": 45.5,
        "Trans Amt": 68.25,
        "Trans Unit Price": 1.50,
        "Trans Ref No": "VEH-001",
        "Trans Vote No": "DEPT-LOGISTICS",
    },
    {
        "Store No": "912",
        "Bin No": "BIN002",
        "Item No": "FUEL002",
        "UOM Code": "L",
        "Item Desc": "Diesel",
        "Item Cat": "Fuel",
        "Trans Date": "20260115",
        "Trans Type": "Issue",
        "Trans Qty": 120.0,
        "Trans Amt": 144.00,
        "Trans Unit Price": 1.20,
        "Trans Ref No": "VEH-002",
        "Trans Vote No": "DEPT-TRANSPORT",
    },
    {
        "Store No": "943",
        "Bin No": "BIN003",
        "Item No": "FUEL001",
        "UOM Code": "L",
        "Item Desc": "Premium Petrol",
        "Item Cat": "Fuel",
        "Trans Date": "20260116",
        "Trans Type": "Issue",
        "Trans Qty": 38.2,
        "Trans Amt": 57.30,
        "Trans Unit Price": 1.50,
        "Trans Ref No": "VEH-003",
        "Trans Vote No": "DEPT-ADMIN",
    },
    {
        "Store No": "913",
        "Bin No": "BIN004",
        "Item No": "FUEL002",
        "UOM Code": "L",
        "Item Desc": "Diesel",
        "Item Cat": "Fuel",
        "Trans Date": "20260116",
        "Trans Type": "Issue",
        "Trans Qty": 95.7,
        "Trans Amt": 114.84,
        "Trans Unit Price": 1.20,
        "Trans Ref No": "VEH-004",
        "Trans Vote No": "DEPT-LOGISTICS",
    },
    {
        "Store No": "914",
        "Bin No": "BIN005",
        "Item No": "FUEL002",
        "UOM Code": "L",
        "Item Desc": "Diesel",
        "Item Cat": "Fuel",
        "Trans Date": "20260117",
        "Trans Type": "Issue",
        "Trans Qty": 150.0,
        "Trans Amt": 180.00,
        "Trans Unit Price": 1.20,
        "Trans Ref No": "VEH-005",
        "Trans Vote No": "DEPT-TRANSPORT",
    },
    {
        "Store No": "911",
        "Bin No": "BIN001",
        "Item No": "FUEL001",
        "UOM Code": "L",
        "Item Desc": "Premium Petrol",
        "Item Cat": "Fuel",
        "Trans Date": "20260117",
        "Trans Type": "Issue",
        "Trans Qty": 52.3,
        "Trans Amt": 78.45,
        "Trans Unit Price": 1.50,
        "Trans Ref No": "VEH-001",
        "Trans Vote No": "DEPT-LOGISTICS",
    },
    {
        "Store No": "915",
        "Bin No": "BIN006",
        "Item No": "FUEL002",
        "UOM Code": "L",
        "Item Desc": "Diesel",
        "Item Cat": "Fuel",
        "Trans Date": "20260118",
        "Trans Type": "Issue",
        "Trans Qty": 88.5,
        "Trans Amt": 106.20,
        "Trans Unit Price": 1.20,
        "Trans Ref No": "VEH-006",
        "Trans Vote No": "DEPT-OPERATIONS",
    },
    {
        "Store No": "943",
        "Bin No": "BIN003",
        "Item No": "FUEL001",
        "UOM Code": "L",
        "Item Desc": "Premium Petrol",
        "Item Cat": "Fuel",
        "Trans Date": "20260118",
        "Trans Type": "Issue",
        "Trans Qty": 41.0,
        "Trans Amt": 61.50,
        "Trans Unit Price": 1.50,
        "Trans Ref No": "VEH-007",
        "Trans Vote No": "DEPT-ADMIN",
    },
    {
        "Store No": "937",
        "Bin No": "BIN007",
        "Item No": "FUEL002",
        "UOM Code": "L",
        "Item Desc": "Diesel",
        "Item Cat": "Fuel",
        "Trans Date": "20260119",
        "Trans Type": "Issue",
        "Trans Qty": 200.0,
        "Trans Amt": 240.00,
        "Trans Unit Price": 1.20,
        "Trans Ref No": "VEH-002",
        "Trans Vote No": "DEPT-TRANSPORT",
    },
    {
        "Store No": "940",
        "Bin No": "BIN008",
        "Item No": "FUEL002",
        "UOM Code": "L",
        "Item Desc": "Diesel",
        "Item Cat": "Fuel",
        "Trans Date": "20260119",
        "Trans Type": "Issue",
        "Trans Qty": 175.5,
        "Trans Amt": 210.60,
        "Trans Unit Price": 1.20,
        "Trans Ref No": "VEH-008",
        "Trans Vote No": "DEPT-LOGISTICS",
    },
];

// Create workbook and worksheet
const wb = XLSX.utils.book_new();
const ws = XLSX.utils.json_to_sheet(sampleData);

// Add worksheet to workbook
XLSX.utils.book_append_sheet(wb, ws, "Fuel Transactions");

// Write to file
XLSX.writeFile(wb, "sample_fuel_data.xlsx");

console.log("✅ Sample Excel file created: sample_fuel_data.xlsx");
