import { PrismaClient } from '@prisma/client';
import 'dotenv/config';

const prisma = new PrismaClient();

// Authoritative cost-centre registry (provided 2026-07-02).
// Format: [department, division, voteNo|null]. Divisions without a vote
// number still register their department. Duplicate vote numbers across
// entries: the FIRST occurrence wins (CostCentre.voteNo is the primary key).
const REGISTRY: [string, string, string | null][] = [
    // DEPARTMENT OF CITY POLICE SERVICES
    ["DEPARTMENT OF CITY POLICE SERVICES", "CRIME PREVENTION UNIT", "4500101100655"],
    ["DEPARTMENT OF CITY POLICE SERVICES", "TRAFFIC MANAGEMENT UNIT", "4520151100655"],
    ["DEPARTMENT OF CITY POLICE SERVICES", "SIGNS AND MARKINGS", "4520101100655"],
    ["DEPARTMENT OF CITY POLICE SERVICES", "HUMAN RESOURCES MANAGEMENT & FINANCE UNIT", "4500151100655"],

    // DEPARTMENT OF ELECTRICITY
    ["DEPARTMENT OF ELECTRICITY", "NETWORK OPERATIONS AND MAINTENACE", "1500101100655"],
    ["DEPARTMENT OF ELECTRICITY", "TRAFFIC LIGHTS", "1500151100655"],
    ["DEPARTMENT OF ELECTRICITY", "PROTECTION & SYSTEMS", "1510051100655"],
    ["DEPARTMENT OF ELECTRICITY", "ENGINEERING SERVICES", null],
    ["DEPARTMENT OF ELECTRICITY", "COMMERCIAL SERVICES", "1500051100655"],
    ["DEPARTMENT OF ELECTRICITY", "ELECTRICITY PRE-PAYMENT", "1510101100655"],
    ["DEPARTMENT OF ELECTRICITY", "ELECTRICITY STREETLIGHTS", "1520101100655"],

    // DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "ECONOMIC DEVELOPMENT", null],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "PARKS, SPORTS, RECREATION & CEMETRIES", "1030101100655"],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "FACILITY DEVELOPMENT", "1030151100655"],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "FACILITY MAINTENANCE EAST", "1030201100655"],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "SPORTS AND RECREATION", "1030301100655"],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "FACILITY MAINTENANCE WEST", "1030251100655"],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "BURIAL & CREMATIONS", "1030351100655"],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "FACILITY MAINTENANCE", "3010051100655"],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "TECHNICAL SUPPORT", "3520051100655"],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "EMERGENCY SERVICES & DISASTER RISK MANAGEMENT", "1040051100655"],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "EMERGENCY SERVICES & DISASTER RISK MANAGEMENT", "1040101100655"],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "HEALTH & ENVIRONMENT SERVICES", "1010051100655"],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "ENVIRONMENT MANAGEMENT", null],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "ENVIRONMENT ENGINEERING", null],
    ["DEPARTMENT OF ECONOMIC DEVELOPMENT AND COMMUNITY SERVICES", "SOCIAL & YOUTH DEVELOPMENT", "1000151100655"],

    // DEPARTMENT OF HOUSING, PROPERTY MANAGEMENT & HUMAN SETTLEMENTS
    ["DEPARTMENT OF HOUSING, PROPERTY MANAGEMENT & HUMAN SETTLEMENTS", "HOUSING & LAND DELIVERY", "4000061100655"],
    ["DEPARTMENT OF HOUSING, PROPERTY MANAGEMENT & HUMAN SETTLEMENTS", "PROPERTY MANAGEMENT", "4000201100655"],
    ["DEPARTMENT OF HOUSING, PROPERTY MANAGEMENT & HUMAN SETTLEMENTS", "VALUATIONS", "4000301100655"],
    ["DEPARTMENT OF HOUSING, PROPERTY MANAGEMENT & HUMAN SETTLEMENTS", "GEOMATICS", "4000251100655"],
    ["DEPARTMENT OF HOUSING, PROPERTY MANAGEMENT & HUMAN SETTLEMENTS", "HUMAN SETTLEMENT", "4000151100655"],
    ["DEPARTMENT OF HOUSING, PROPERTY MANAGEMENT & HUMAN SETTLEMENTS", "ARCHITECTURE", "3010251100655"],

    // DEPARTMENT OF FINANCE & CUSTOMER SERVICES
    ["DEPARTMENT OF FINANCE & CUSTOMER SERVICES", "DEBT AND RISK MANAGEMENT", "2000151100655"],
    ["DEPARTMENT OF FINANCE & CUSTOMER SERVICES", "CASH MANAGEMENT", "2000051100655"],
    ["DEPARTMENT OF FINANCE & CUSTOMER SERVICES", "CUSTOMER SERVICES", "4000201100655"], // conflict: first seen under HOUSING/PROPERTY MANAGEMENT
    ["DEPARTMENT OF FINANCE & CUSTOMER SERVICES", "FINANCIAL REPORTING", "2010051100655"],
    ["DEPARTMENT OF FINANCE & CUSTOMER SERVICES", "MUNICIPAL FLEET", "6000051100655"],
    ["DEPARTMENT OF FINANCE & CUSTOMER SERVICES", "MUNICIPAL FLEET", "6010551100655"],
    ["DEPARTMENT OF FINANCE & CUSTOMER SERVICES", "COMMERCIAL SERVICES", "4000151100655"], // conflict: first seen under HOUSING/HUMAN SETTLEMENT
    ["DEPARTMENT OF FINANCE & CUSTOMER SERVICES", "PROCUREMENT", "4000201100655"], // conflict
    ["DEPARTMENT OF FINANCE & CUSTOMER SERVICES", "PROCUREMENT", "2000101100655"],
    ["DEPARTMENT OF FINANCE & CUSTOMER SERVICES", "REVENUE MANAGEMENT", "2020051100655"],

    // DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "BUILT ENVIRONMENT", null],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "BULK WATER & WASTE WATER", "3020051100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "BULK WATER & WASTE WATER", "3020151100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "BULK WATER & WASTE WATER", "3020201100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "BULK WATER & WASTE WATER", "3020251100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "BULK WATER & WASTE WATER", "3020301100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "BULK WATER & WASTE WATER", "3020351100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "BULK WATER & WASTE WATER", "3020401100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "BULK WATER & WASTE WATER", "3020501100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "WATER SERVICES BOREHOLES", "3040101100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "ENGINEERING SERVICES", "3040051100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "ROADS & STORM WATER", "3050051100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "ROADS & STORM WATER", "3050101100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "GRADERS - ROADS", "6010101100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "INFRASTRUCTURE", "6010401100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "INFRASTRUCTURE", "6010551100655"], // conflict: first seen under FINANCE/MUNICIPAL FLEET
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "SCIENTIFIC SERVICES", "3000151100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "SOLID WASTE MANAGEMENT", "3030101100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "SOLID WASTE MANAGEMENT", "3030151100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "SOLID WASTE MANAGEMENT", "3030201100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "SOLID WASTE MANAGEMENT", "3030301100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "TANKERS - ROADS", "6010451100655"],
    ["DEPARTMENT OF INFRASTRUCTURE WATER & TECHNICAL SERVICES", "ROADS", "6010351100655"],

    // DEPARTMENT OF INFORMATION, COMMUNICATION & TECHNOLOGY
    ["DEPARTMENT OF INFORMATION, COMMUNICATION & TECHNOLOGY", "ICT CORE TECHNOLOGY INFRASTRUCTURE", "2000251100655"],
    ["DEPARTMENT OF INFORMATION, COMMUNICATION & TECHNOLOGY", "ICT CORE TECHNOLOGY INFRASTRUCTURE", "3520051100655"], // conflict: first seen under ECONOMIC DEV/TECHNICAL SUPPORT
    ["DEPARTMENT OF INFORMATION, COMMUNICATION & TECHNOLOGY", "BUSINESS SYSTEMS & INFORMATION MANAGEMENT", null],
    ["DEPARTMENT OF INFORMATION, COMMUNICATION & TECHNOLOGY", "ICT SERVICE MANAGEMNT", null],
    ["DEPARTMENT OF INFORMATION, COMMUNICATION & TECHNOLOGY", "ICT GOVERNANCE, SECURITY & COMPLIANCE", null],

    // DEPARTMENT OF HUMAN CAPITAL & CORPORATE SERVICES
    ["DEPARTMENT OF HUMAN CAPITAL & CORPORATE SERVICES", "ORGANISATIONAL DEVELOPMENT & HUMAN RESOURCES DEVELOPMENT", null],
    ["DEPARTMENT OF HUMAN CAPITAL & CORPORATE SERVICES", "STAFFING & REMUNERATION", null],
    ["DEPARTMENT OF HUMAN CAPITAL & CORPORATE SERVICES", "LABOUR RELATIONS", null],
    ["DEPARTMENT OF HUMAN CAPITAL & CORPORATE SERVICES", "OCCUPATIONAL HEALTH, SAFETY AND WELLNESS", "2510101100655"],
    ["DEPARTMENT OF HUMAN CAPITAL & CORPORATE SERVICES", "CORPORATE SERVICES", "2510051100655"],
    ["DEPARTMENT OF HUMAN CAPITAL & CORPORATE SERVICES", "GENERAL", "2500101100655"],

    // OFFICE OF THE CHIEF EXECUTIVE OFFICER
    ["OFFICE OF THE CHIEF EXECUTIVE OFFICER", "INTERNAL AUDIT", null],
    ["OFFICE OF THE CHIEF EXECUTIVE OFFICER", "CORPORATE COMMUNICATIONS, MARKETING & PUBLIC PARTICIPATION", "510051100655"],
    ["OFFICE OF THE CHIEF EXECUTIVE OFFICER", "CORPORATE COMMUNICATIONS, MARKETING & PUBLIC PARTICIPATION", "510301100655"],
    ["OFFICE OF THE CHIEF EXECUTIVE OFFICER", "CORPORATE COMMUNICATIONS, MARKETING & PUBLIC PARTICIPATION", "510401100655"],
    ["OFFICE OF THE CHIEF EXECUTIVE OFFICER", "LEGAL SERVICES", null],
    ["OFFICE OF THE CHIEF EXECUTIVE OFFICER", "STRATEGY AND ORGNISATIONAL PERFORMANCE UNIT", null],
    ["OFFICE OF THE CHIEF EXECUTIVE OFFICER", "MAYORAL & COUNCIL AFFAIRS", "520051100655"],
    ["OFFICE OF THE CHIEF EXECUTIVE OFFICER", "EXTERNAL RELATIONS & NETWORKING", "520101100655"],

    // DEPARTMENT OF URBAN AND TRANSPORT PLANNING
    ["DEPARTMENT OF URBAN AND TRANSPORT PLANNING", "INFO", "1020151100655"],
    ["DEPARTMENT OF URBAN AND TRANSPORT PLANNING", "BUSINESS DEVELOPEMENT", "1020051100655"],
    ["DEPARTMENT OF URBAN AND TRANSPORT PLANNING", "BUILDING CONTROL", "5000201100655"],
    ["DEPARTMENT OF URBAN AND TRANSPORT PLANNING", "BUILDING CONTROL", "1030101100655"], // conflict: first seen under ECONOMIC DEV/PARKS
    ["DEPARTMENT OF URBAN AND TRANSPORT PLANNING", "PLANNING, DESIGN & TRAFFIC FLOW", "5010151100655"],
    ["DEPARTMENT OF URBAN AND TRANSPORT PLANNING", "ROADS PLANNING & TRAFFIC FLOW", "5010051100655"],
    ["DEPARTMENT OF URBAN AND TRANSPORT PLANNING", "SUSTAINABLE DEVELOPMENT", "5000181100655"],
    ["DEPARTMENT OF URBAN AND TRANSPORT PLANNING", "PUBLIC TRANSPORT", "5000111100655"],
    ["DEPARTMENT OF URBAN AND TRANSPORT PLANNING", "URBAN POLICY", "5000131150275"],
    ["DEPARTMENT OF URBAN AND TRANSPORT PLANNING", "URBAN POLICY", "5000131100655"],
    ["DEPARTMENT OF URBAN AND TRANSPORT PLANNING", "BUILDING MAINTANANCE", "6020051100655"],
];

async function main() {
    // 1. Departments (independent registry)
    const departments = [...new Set(REGISTRY.map(([d]) => d))];
    for (const name of departments) {
        await prisma.department.upsert({ where: { name }, update: {}, create: { name } });
    }
    console.log(`Departments registered: ${departments.length}`);

    // 2. Cost centres — first occurrence of a voteNo wins
    const seen = new Map<string, { department: string; division: string }>();
    const conflicts: string[] = [];
    for (const [department, division, voteNo] of REGISTRY) {
        if (!voteNo) continue;
        if (seen.has(voteNo)) {
            const first = seen.get(voteNo)!;
            if (first.department !== department || first.division !== division) {
                conflicts.push(`${voteNo}: kept "${first.department} / ${first.division}", skipped "${department} / ${division}"`);
            }
            continue;
        }
        seen.set(voteNo, { department, division });
    }

    let created = 0, updated = 0;
    for (const [voteNo, { department, division }] of seen) {
        const existing = await prisma.costCentre.findUnique({ where: { voteNo } });
        if (existing) {
            if (existing.department !== department || existing.division !== division) {
                await prisma.costCentre.update({ where: { voteNo }, data: { department, division } });
                updated++;
            }
        } else {
            await prisma.costCentre.create({ data: { voteNo, department, division } });
            created++;
        }
    }

    console.log(`Cost centres: ${seen.size} unique votes | created ${created}, updated ${updated}`);
    if (conflicts.length) {
        console.log(`\nDuplicate votes resolved (first occurrence kept):`);
        conflicts.forEach(c => console.log('  - ' + c));
    }

    const totalCC = await prisma.costCentre.count();
    console.log(`\nTotal cost centres in DB: ${totalCC}`);
}

main().finally(() => prisma.$disconnect());
